//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ReportsDBModel", "FK_DriverDevice", "Device", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReportingService.Device), "Driver", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportingService.Driver), true)]
[assembly: EdmRelationshipAttribute("ReportsDBModel", "FK_Users_Roles", "Role", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ReportingService.Role), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReportingService.User), true)]

#endregion

namespace ReportingService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ReportsDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ReportsDBEntities object using the connection string found in the 'ReportsDBEntities' section of the application configuration file.
        /// </summary>
        public ReportsDBEntities() : base("name=ReportsDBEntities", "ReportsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReportsDBEntities object.
        /// </summary>
        public ReportsDBEntities(string connectionString) : base(connectionString, "ReportsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ReportsDBEntities object.
        /// </summary>
        public ReportsDBEntities(EntityConnection connection) : base(connection, "ReportsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NormalReport> NormalReports
        {
            get
            {
                if ((_NormalReports == null))
                {
                    _NormalReports = base.CreateObjectSet<NormalReport>("NormalReports");
                }
                return _NormalReports;
            }
        }
        private ObjectSet<NormalReport> _NormalReports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Statistic> Statistics
        {
            get
            {
                if ((_Statistics == null))
                {
                    _Statistics = base.CreateObjectSet<Statistic>("Statistics");
                }
                return _Statistics;
            }
        }
        private ObjectSet<Statistic> _Statistics;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BugReport> BugReports
        {
            get
            {
                if ((_BugReports == null))
                {
                    _BugReports = base.CreateObjectSet<BugReport>("BugReports");
                }
                return _BugReports;
            }
        }
        private ObjectSet<BugReport> _BugReports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Version> Versions
        {
            get
            {
                if ((_Versions == null))
                {
                    _Versions = base.CreateObjectSet<Version>("Versions");
                }
                return _Versions;
            }
        }
        private ObjectSet<Version> _Versions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Device> Devices
        {
            get
            {
                if ((_Devices == null))
                {
                    _Devices = base.CreateObjectSet<Device>("Devices");
                }
                return _Devices;
            }
        }
        private ObjectSet<Device> _Devices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Driver> Drivers
        {
            get
            {
                if ((_Drivers == null))
                {
                    _Drivers = base.CreateObjectSet<Driver>("Drivers");
                }
                return _Drivers;
            }
        }
        private ObjectSet<Driver> _Drivers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NormalReports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNormalReports(NormalReport normalReport)
        {
            base.AddObject("NormalReports", normalReport);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Statistics EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatistics(Statistic statistic)
        {
            base.AddObject("Statistics", statistic);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BugReports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBugReports(BugReport bugReport)
        {
            base.AddObject("BugReports", bugReport);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Versions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVersions(Version version)
        {
            base.AddObject("Versions", version);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Devices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDevices(Device device)
        {
            base.AddObject("Devices", device);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Drivers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDrivers(Driver driver)
        {
            base.AddObject("Drivers", driver);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportsDBModel", Name="BugReport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BugReport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BugReport object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="version">Initial value of the Version property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="mAC">Initial value of the MAC property.</param>
        /// <param name="iP">Initial value of the IP property.</param>
        /// <param name="oS">Initial value of the OS property.</param>
        /// <param name="hostName">Initial value of the HostName property.</param>
        /// <param name="bugStackTrace">Initial value of the BugStackTrace property.</param>
        /// <param name="bugType">Initial value of the BugType property.</param>
        /// <param name="bugMessage">Initial value of the BugMessage property.</param>
        /// <param name="bugUserInput">Initial value of the BugUserInput property.</param>
        /// <param name="bugTargetSite">Initial value of the BugTargetSite property.</param>
        /// <param name="bugSource">Initial value of the BugSource property.</param>
        public static BugReport CreateBugReport(global::System.Int32 id, global::System.String version, global::System.DateTime date, global::System.String mAC, global::System.String iP, global::System.String oS, global::System.String hostName, global::System.String bugStackTrace, global::System.String bugType, global::System.String bugMessage, global::System.String bugUserInput, global::System.String bugTargetSite, global::System.String bugSource)
        {
            BugReport bugReport = new BugReport();
            bugReport.Id = id;
            bugReport.Version = version;
            bugReport.Date = date;
            bugReport.MAC = mAC;
            bugReport.IP = iP;
            bugReport.OS = oS;
            bugReport.HostName = hostName;
            bugReport.BugStackTrace = bugStackTrace;
            bugReport.BugType = bugType;
            bugReport.BugMessage = bugMessage;
            bugReport.BugUserInput = bugUserInput;
            bugReport.BugTargetSite = bugTargetSite;
            bugReport.BugSource = bugSource;
            return bugReport;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.String _Version;
        partial void OnVersionChanging(global::System.String value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAC
        {
            get
            {
                return _MAC;
            }
            set
            {
                OnMACChanging(value);
                ReportPropertyChanging("MAC");
                _MAC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MAC");
                OnMACChanged();
            }
        }
        private global::System.String _MAC;
        partial void OnMACChanging(global::System.String value);
        partial void OnMACChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OS
        {
            get
            {
                return _OS;
            }
            set
            {
                OnOSChanging(value);
                ReportPropertyChanging("OS");
                _OS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OS");
                OnOSChanged();
            }
        }
        private global::System.String _OS;
        partial void OnOSChanging(global::System.String value);
        partial void OnOSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HostName
        {
            get
            {
                return _HostName;
            }
            set
            {
                OnHostNameChanging(value);
                ReportPropertyChanging("HostName");
                _HostName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HostName");
                OnHostNameChanged();
            }
        }
        private global::System.String _HostName;
        partial void OnHostNameChanging(global::System.String value);
        partial void OnHostNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BugStackTrace
        {
            get
            {
                return _BugStackTrace;
            }
            set
            {
                OnBugStackTraceChanging(value);
                ReportPropertyChanging("BugStackTrace");
                _BugStackTrace = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BugStackTrace");
                OnBugStackTraceChanged();
            }
        }
        private global::System.String _BugStackTrace;
        partial void OnBugStackTraceChanging(global::System.String value);
        partial void OnBugStackTraceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BugType
        {
            get
            {
                return _BugType;
            }
            set
            {
                OnBugTypeChanging(value);
                ReportPropertyChanging("BugType");
                _BugType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BugType");
                OnBugTypeChanged();
            }
        }
        private global::System.String _BugType;
        partial void OnBugTypeChanging(global::System.String value);
        partial void OnBugTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BugMessage
        {
            get
            {
                return _BugMessage;
            }
            set
            {
                OnBugMessageChanging(value);
                ReportPropertyChanging("BugMessage");
                _BugMessage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BugMessage");
                OnBugMessageChanged();
            }
        }
        private global::System.String _BugMessage;
        partial void OnBugMessageChanging(global::System.String value);
        partial void OnBugMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BugUserInput
        {
            get
            {
                return _BugUserInput;
            }
            set
            {
                OnBugUserInputChanging(value);
                ReportPropertyChanging("BugUserInput");
                _BugUserInput = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BugUserInput");
                OnBugUserInputChanged();
            }
        }
        private global::System.String _BugUserInput;
        partial void OnBugUserInputChanging(global::System.String value);
        partial void OnBugUserInputChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BugTargetSite
        {
            get
            {
                return _BugTargetSite;
            }
            set
            {
                OnBugTargetSiteChanging(value);
                ReportPropertyChanging("BugTargetSite");
                _BugTargetSite = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BugTargetSite");
                OnBugTargetSiteChanged();
            }
        }
        private global::System.String _BugTargetSite;
        partial void OnBugTargetSiteChanging(global::System.String value);
        partial void OnBugTargetSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BugSource
        {
            get
            {
                return _BugSource;
            }
            set
            {
                OnBugSourceChanging(value);
                ReportPropertyChanging("BugSource");
                _BugSource = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BugSource");
                OnBugSourceChanged();
            }
        }
        private global::System.String _BugSource;
        partial void OnBugSourceChanging(global::System.String value);
        partial void OnBugSourceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportsDBModel", Name="Device")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Device : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Device object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="deviceID">Initial value of the DeviceID property.</param>
        /// <param name="vendor">Initial value of the Vendor property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="hardwareID">Initial value of the HardwareID property.</param>
        /// <param name="compatibleID">Initial value of the CompatibleID property.</param>
        public static Device CreateDevice(global::System.Int32 id, global::System.String deviceID, global::System.String vendor, global::System.String name, global::System.String description, global::System.String hardwareID, global::System.String compatibleID)
        {
            Device device = new Device();
            device.Id = id;
            device.DeviceID = deviceID;
            device.Vendor = vendor;
            device.Name = name;
            device.Description = description;
            device.HardwareID = hardwareID;
            device.CompatibleID = compatibleID;
            return device;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DeviceID
        {
            get
            {
                return _DeviceID;
            }
            set
            {
                OnDeviceIDChanging(value);
                ReportPropertyChanging("DeviceID");
                _DeviceID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DeviceID");
                OnDeviceIDChanged();
            }
        }
        private global::System.String _DeviceID;
        partial void OnDeviceIDChanging(global::System.String value);
        partial void OnDeviceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Vendor
        {
            get
            {
                return _Vendor;
            }
            set
            {
                OnVendorChanging(value);
                ReportPropertyChanging("Vendor");
                _Vendor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Vendor");
                OnVendorChanged();
            }
        }
        private global::System.String _Vendor;
        partial void OnVendorChanging(global::System.String value);
        partial void OnVendorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HardwareID
        {
            get
            {
                return _HardwareID;
            }
            set
            {
                OnHardwareIDChanging(value);
                ReportPropertyChanging("HardwareID");
                _HardwareID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HardwareID");
                OnHardwareIDChanged();
            }
        }
        private global::System.String _HardwareID;
        partial void OnHardwareIDChanging(global::System.String value);
        partial void OnHardwareIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompatibleID
        {
            get
            {
                return _CompatibleID;
            }
            set
            {
                OnCompatibleIDChanging(value);
                ReportPropertyChanging("CompatibleID");
                _CompatibleID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CompatibleID");
                OnCompatibleIDChanged();
            }
        }
        private global::System.String _CompatibleID;
        partial void OnCompatibleIDChanging(global::System.String value);
        partial void OnCompatibleIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReportsDBModel", "FK_DriverDevice", "Driver")]
        public EntityCollection<Driver> Drivers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Driver>("ReportsDBModel.FK_DriverDevice", "Driver");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Driver>("ReportsDBModel.FK_DriverDevice", "Driver", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportsDBModel", Name="Driver")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Driver : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Driver object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="downloadLink">Initial value of the DownloadLink property.</param>
        /// <param name="version">Initial value of the Version property.</param>
        /// <param name="versionDate">Initial value of the VersionDate property.</param>
        /// <param name="postDate">Initial value of the PostDate property.</param>
        /// <param name="installCommand">Initial value of the InstallCommand property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="device_Id">Initial value of the Device_Id property.</param>
        public static Driver CreateDriver(global::System.Int32 id, global::System.String downloadLink, global::System.String version, global::System.DateTime versionDate, global::System.DateTime postDate, global::System.String installCommand, global::System.String fileName, global::System.Int32 device_Id)
        {
            Driver driver = new Driver();
            driver.Id = id;
            driver.DownloadLink = downloadLink;
            driver.Version = version;
            driver.VersionDate = versionDate;
            driver.PostDate = postDate;
            driver.InstallCommand = installCommand;
            driver.FileName = fileName;
            driver.Device_Id = device_Id;
            return driver;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DownloadLink
        {
            get
            {
                return _DownloadLink;
            }
            set
            {
                OnDownloadLinkChanging(value);
                ReportPropertyChanging("DownloadLink");
                _DownloadLink = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DownloadLink");
                OnDownloadLinkChanged();
            }
        }
        private global::System.String _DownloadLink;
        partial void OnDownloadLinkChanging(global::System.String value);
        partial void OnDownloadLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.String _Version;
        partial void OnVersionChanging(global::System.String value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime VersionDate
        {
            get
            {
                return _VersionDate;
            }
            set
            {
                OnVersionDateChanging(value);
                ReportPropertyChanging("VersionDate");
                _VersionDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VersionDate");
                OnVersionDateChanged();
            }
        }
        private global::System.DateTime _VersionDate;
        partial void OnVersionDateChanging(global::System.DateTime value);
        partial void OnVersionDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PostDate
        {
            get
            {
                return _PostDate;
            }
            set
            {
                OnPostDateChanging(value);
                ReportPropertyChanging("PostDate");
                _PostDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostDate");
                OnPostDateChanged();
            }
        }
        private global::System.DateTime _PostDate;
        partial void OnPostDateChanging(global::System.DateTime value);
        partial void OnPostDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InstallCommand
        {
            get
            {
                return _InstallCommand;
            }
            set
            {
                OnInstallCommandChanging(value);
                ReportPropertyChanging("InstallCommand");
                _InstallCommand = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("InstallCommand");
                OnInstallCommandChanged();
            }
        }
        private global::System.String _InstallCommand;
        partial void OnInstallCommandChanging(global::System.String value);
        partial void OnInstallCommandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Device_Id
        {
            get
            {
                return _Device_Id;
            }
            set
            {
                OnDevice_IdChanging(value);
                ReportPropertyChanging("Device_Id");
                _Device_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Device_Id");
                OnDevice_IdChanged();
            }
        }
        private global::System.Int32 _Device_Id;
        partial void OnDevice_IdChanging(global::System.Int32 value);
        partial void OnDevice_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReportsDBModel", "FK_DriverDevice", "Device")]
        public Device Device
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("ReportsDBModel.FK_DriverDevice", "Device").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("ReportsDBModel.FK_DriverDevice", "Device").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Device> DeviceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("ReportsDBModel.FK_DriverDevice", "Device");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Device>("ReportsDBModel.FK_DriverDevice", "Device", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportsDBModel", Name="NormalReport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NormalReport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NormalReport object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="version">Initial value of the Version property.</param>
        /// <param name="action">Initial value of the Action property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="mAC">Initial value of the MAC property.</param>
        /// <param name="iP">Initial value of the IP property.</param>
        /// <param name="oS">Initial value of the OS property.</param>
        /// <param name="hostName">Initial value of the HostName property.</param>
        public static NormalReport CreateNormalReport(global::System.Int32 id, global::System.String version, global::System.String action, global::System.DateTime date, global::System.String mAC, global::System.String iP, global::System.String oS, global::System.String hostName)
        {
            NormalReport normalReport = new NormalReport();
            normalReport.Id = id;
            normalReport.Version = version;
            normalReport.Action = action;
            normalReport.Date = date;
            normalReport.MAC = mAC;
            normalReport.IP = iP;
            normalReport.OS = oS;
            normalReport.HostName = hostName;
            return normalReport;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.String _Version;
        partial void OnVersionChanging(global::System.String value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MAC
        {
            get
            {
                return _MAC;
            }
            set
            {
                OnMACChanging(value);
                ReportPropertyChanging("MAC");
                _MAC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MAC");
                OnMACChanged();
            }
        }
        private global::System.String _MAC;
        partial void OnMACChanging(global::System.String value);
        partial void OnMACChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OS
        {
            get
            {
                return _OS;
            }
            set
            {
                OnOSChanging(value);
                ReportPropertyChanging("OS");
                _OS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OS");
                OnOSChanged();
            }
        }
        private global::System.String _OS;
        partial void OnOSChanging(global::System.String value);
        partial void OnOSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HostName
        {
            get
            {
                return _HostName;
            }
            set
            {
                OnHostNameChanging(value);
                ReportPropertyChanging("HostName");
                _HostName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HostName");
                OnHostNameChanged();
            }
        }
        private global::System.String _HostName;
        partial void OnHostNameChanging(global::System.String value);
        partial void OnHostNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportsDBModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="roleid">Initial value of the Roleid property.</param>
        /// <param name="roletype">Initial value of the Roletype property.</param>
        public static Role CreateRole(global::System.Int32 roleid, global::System.String roletype)
        {
            Role role = new Role();
            role.Roleid = roleid;
            role.Roletype = roletype;
            return role;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Roleid
        {
            get
            {
                return _Roleid;
            }
            set
            {
                if (_Roleid != value)
                {
                    OnRoleidChanging(value);
                    ReportPropertyChanging("Roleid");
                    _Roleid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Roleid");
                    OnRoleidChanged();
                }
            }
        }
        private global::System.Int32 _Roleid;
        partial void OnRoleidChanging(global::System.Int32 value);
        partial void OnRoleidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Roletype
        {
            get
            {
                return _Roletype;
            }
            set
            {
                OnRoletypeChanging(value);
                ReportPropertyChanging("Roletype");
                _Roletype = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Roletype");
                OnRoletypeChanged();
            }
        }
        private global::System.String _Roletype;
        partial void OnRoletypeChanging(global::System.String value);
        partial void OnRoletypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReportsDBModel", "FK_Users_Roles", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("ReportsDBModel.FK_Users_Roles", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("ReportsDBModel.FK_Users_Roles", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportsDBModel", Name="Statistic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Statistic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Statistic object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="version">Initial value of the Version property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="count">Initial value of the Count property.</param>
        public static Statistic CreateStatistic(global::System.Int32 id, global::System.String version, global::System.String type, global::System.Int32 count)
        {
            Statistic statistic = new Statistic();
            statistic.Id = id;
            statistic.Version = version;
            statistic.Type = type;
            statistic.Count = count;
            return statistic;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.String _Version;
        partial void OnVersionChanging(global::System.String value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private global::System.Int32 _Count;
        partial void OnCountChanging(global::System.Int32 value);
        partial void OnCountChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportsDBModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="roleid">Initial value of the Roleid property.</param>
        /// <param name="userid">Initial value of the Userid property.</param>
        public static User CreateUser(global::System.String username, global::System.String password, global::System.Int32 roleid, global::System.Int32 userid)
        {
            User user = new User();
            user.Username = username;
            user.Password = password;
            user.Roleid = roleid;
            user.Userid = userid;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Roleid
        {
            get
            {
                return _Roleid;
            }
            set
            {
                OnRoleidChanging(value);
                ReportPropertyChanging("Roleid");
                _Roleid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Roleid");
                OnRoleidChanged();
            }
        }
        private global::System.Int32 _Roleid;
        partial void OnRoleidChanging(global::System.Int32 value);
        partial void OnRoleidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Userid
        {
            get
            {
                return _Userid;
            }
            set
            {
                if (_Userid != value)
                {
                    OnUseridChanging(value);
                    ReportPropertyChanging("Userid");
                    _Userid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Userid");
                    OnUseridChanged();
                }
            }
        }
        private global::System.Int32 _Userid;
        partial void OnUseridChanging(global::System.Int32 value);
        partial void OnUseridChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReportsDBModel", "FK_Users_Roles", "Role")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("ReportsDBModel.FK_Users_Roles", "Role").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("ReportsDBModel.FK_Users_Roles", "Role").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("ReportsDBModel.FK_Users_Roles", "Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("ReportsDBModel.FK_Users_Roles", "Role", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReportsDBModel", Name="Version")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Version : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Version object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="downloadLink">Initial value of the DownloadLink property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Version CreateVersion(global::System.Int32 id, global::System.String number, global::System.String downloadLink, global::System.String date)
        {
            Version version = new Version();
            version.Id = id;
            version.Number = number;
            version.DownloadLink = downloadLink;
            version.Date = date;
            return version;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.String _Number;
        partial void OnNumberChanging(global::System.String value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DownloadLink
        {
            get
            {
                return _DownloadLink;
            }
            set
            {
                OnDownloadLinkChanging(value);
                ReportPropertyChanging("DownloadLink");
                _DownloadLink = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DownloadLink");
                OnDownloadLinkChanged();
            }
        }
        private global::System.String _DownloadLink;
        partial void OnDownloadLinkChanging(global::System.String value);
        partial void OnDownloadLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.String _Date;
        partial void OnDateChanging(global::System.String value);
        partial void OnDateChanged();

        #endregion
    
    }

    #endregion
    
}
