//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeDriverScout.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeDriverScout.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All drivers are up to date! ähnelt.
        /// </summary>
        internal static string AllDriversAreUpToDate {
            get {
                return ResourceManager.GetString("AllDriversAreUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All rights reserved. ähnelt.
        /// </summary>
        internal static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automated Scan ähnelt.
        /// </summary>
        internal static string AutomatedScan {
            get {
                return ResourceManager.GetString("AutomatedScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-Update Drivers ähnelt.
        /// </summary>
        internal static string AutoUpdateDrivers {
            get {
                return ResourceManager.GetString("AutoUpdateDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup &amp; Restore ähnelt.
        /// </summary>
        internal static string BackupAndRestore {
            get {
                return ResourceManager.GetString("BackupAndRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup finished ähnelt.
        /// </summary>
        internal static string BackupFinished {
            get {
                return ResourceManager.GetString("BackupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove the exclusions you created in the Driver Scan ähnelt.
        /// </summary>
        internal static string BackupFinishedText {
            get {
                return ResourceManager.GetString("BackupFinishedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup ähnelt.
        /// </summary>
        internal static string BackupRadioBtnTitle {
            get {
                return ResourceManager.GetString("BackupRadioBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup all or specifiy the device drivers of your system, in order to create copies of these drivers that you can revert to later.  ähnelt.
        /// </summary>
        internal static string BackupText {
            get {
                return ResourceManager.GetString("BackupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BACKUP  TYPE ähnelt.
        /// </summary>
        internal static string BackupType {
            get {
                return ResourceManager.GetString("BackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel Scan ähnelt.
        /// </summary>
        internal static string CancelScan {
            get {
                return ResourceManager.GetString("CancelScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please, check Backups folder in your Preferences ähnelt.
        /// </summary>
        internal static string CheckBackupsFolder {
            get {
                return ResourceManager.GetString("CheckBackupsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please, check your download folder in preferences ähnelt.
        /// </summary>
        internal static string CheckDownloadFolder {
            get {
                return ResourceManager.GetString("CheckDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Preferences ähnelt.
        /// </summary>
        internal static string CheckPreferences {
            get {
                return ResourceManager.GetString("CheckPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose the destination directory ähnelt.
        /// </summary>
        internal static string ChooseDestination {
            get {
                return ResourceManager.GetString("ChooseDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please, choose the destination directory ähnelt.
        /// </summary>
        internal static string ChooseDestinationDirectory {
            get {
                return ResourceManager.GetString("ChooseDestinationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close button behaviour: ähnelt.
        /// </summary>
        internal static string CloseButtonBehaviour {
            get {
                return ResourceManager.GetString("CloseButtonBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contacting Server to check updates ähnelt.
        /// </summary>
        internal static string ContactingServer {
            get {
                return ResourceManager.GetString("ContactingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Backup ähnelt.
        /// </summary>
        internal static string CreateBackup {
            get {
                return ResourceManager.GetString("CreateBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day: ähnelt.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die days ago ähnelt.
        /// </summary>
        internal static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date of current version: ähnelt.
        /// </summary>
        internal static string DetailCurrentDriverDate {
            get {
                return ResourceManager.GetString("DetailCurrentDriverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string DetailName {
            get {
                return ResourceManager.GetString("DetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date of new version: ähnelt.
        /// </summary>
        internal static string DetailNewDriverDate {
            get {
                return ResourceManager.GetString("DetailNewDriverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Completed  ähnelt.
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download complete! ähnelt.
        /// </summary>
        internal static string DownloadCompleteMessage {
            get {
                return ResourceManager.GetString("DownloadCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Driver ähnelt.
        /// </summary>
        internal static string DownloadDriver {
            get {
                return ResourceManager.GetString("DownloadDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading driver for:  ähnelt.
        /// </summary>
        internal static string DownloadingDriver {
            get {
                return ResourceManager.GetString("DownloadingDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloaded {0} of {1} ähnelt.
        /// </summary>
        internal static string DownloadStatus {
            get {
                return ResourceManager.GetString("DownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driver Information Details ähnelt.
        /// </summary>
        internal static string DriverDetailInfoPopupTitle {
            get {
                return ResourceManager.GetString("DriverDetailInfoPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DRIVER DETAILS ähnelt.
        /// </summary>
        internal static string DriverDetails {
            get {
                return ResourceManager.GetString("DriverDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driver Downloading &amp; Installation ähnelt.
        /// </summary>
        internal static string DriverDownloadingAndInstallation {
            get {
                return ResourceManager.GetString("DriverDownloadingAndInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} excluded from scans ähnelt.
        /// </summary>
        internal static string DriverExcluded {
            get {
                return ResourceManager.GetString("DriverExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driver Info ähnelt.
        /// </summary>
        internal static string DriverInfo {
            get {
                return ResourceManager.GetString("DriverInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driver list is still loading ähnelt.
        /// </summary>
        internal static string DriverListLoading {
            get {
                return ResourceManager.GetString("DriverListLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The driver list is still being loaded in the background. Please wait a moment and then try the backup again. ähnelt.
        /// </summary>
        internal static string DriverListLoadingText {
            get {
                return ResourceManager.GetString("DriverListLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup of {0} drivers is completed. ähnelt.
        /// </summary>
        internal static string DriversBackupedSuccesfully {
            get {
                return ResourceManager.GetString("DriversBackupedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driver Scan ähnelt.
        /// </summary>
        internal static string DriverScan {
            get {
                return ResourceManager.GetString("DriverScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driver Scan Results ähnelt.
        /// </summary>
        internal static string DriverScanResults {
            get {
                return ResourceManager.GetString("DriverScanResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die drivers downloaded ähnelt.
        /// </summary>
        internal static string DriversDownloaded {
            get {
                return ResourceManager.GetString("DriversDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die drivers restored successfully ähnelt.
        /// </summary>
        internal static string DriversRestoredSuccesfully {
            get {
                return ResourceManager.GetString("DriversRestoredSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driver Update ähnelt.
        /// </summary>
        internal static string DriverUpdate {
            get {
                return ResourceManager.GetString("DriverUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every day ähnelt.
        /// </summary>
        internal static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every month ähnelt.
        /// </summary>
        internal static string EveryMonth {
            get {
                return ResourceManager.GetString("EveryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every week ähnelt.
        /// </summary>
        internal static string EveryWeek {
            get {
                return ResourceManager.GetString("EveryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exclude ähnelt.
        /// </summary>
        internal static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exclude device ähnelt.
        /// </summary>
        internal static string ExcludeDevice {
            get {
                return ResourceManager.GetString("ExcludeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exclude from scans ähnelt.
        /// </summary>
        internal static string ExcludeFromScans {
            get {
                return ResourceManager.GetString("ExcludeFromScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Like ähnelt.
        /// </summary>
        internal static string FacebookLike {
            get {
                return ResourceManager.GetString("FacebookLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.freemium.com/fsu/facebook ähnelt.
        /// </summary>
        internal static string FBUrl {
            get {
                return ResourceManager.GetString("FBUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback Report ähnelt.
        /// </summary>
        internal static string FeedbackReport {
            get {
                return ResourceManager.GetString("FeedbackReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://freemium.com/contact/fdc/ ähnelt.
        /// </summary>
        internal static string FeedbackUrl {
            get {
                return ResourceManager.GetString("FeedbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MORE FREE PREMIUM SOFTWARE ähnelt.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Friday ähnelt.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die from scans? ähnelt.
        /// </summary>
        internal static string FromScans {
            get {
                return ResourceManager.GetString("FromScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -77 ähnelt.
        /// </summary>
        internal static string GoogleMargin {
            get {
                return ResourceManager.GetString("GoogleMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.freemium.com/fsu/googleplus ähnelt.
        /// </summary>
        internal static string GooglePlusUrl {
            get {
                return ResourceManager.GetString("GooglePlusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading... ähnelt.
        /// </summary>
        internal static string InitialLoading {
            get {
                return ResourceManager.GetString("InitialLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INSTALLATION PROGRESS ähnelt.
        /// </summary>
        internal static string InstallationProgress {
            get {
                return ResourceManager.GetString("InstallationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installed ähnelt.
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installing driver for: ähnelt.
        /// </summary>
        internal static string InstallingDriver {
            get {
                return ResourceManager.GetString("InstallingDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Scan: ähnelt.
        /// </summary>
        internal static string LastScan {
            get {
                return ResourceManager.GetString("LastScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Launch at startup ähnelt.
        /// </summary>
        internal static string LaunchAtStartup {
            get {
                return ResourceManager.GetString("LaunchAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage your Scan Exclusions ähnelt.
        /// </summary>
        internal static string ManageScanExclusions {
            get {
                return ResourceManager.GetString("ManageScanExclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove the exclusions you created in the Driver Scan ähnelt.
        /// </summary>
        internal static string ManageScanExclusionsText {
            get {
                return ResourceManager.GetString("ManageScanExclusionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual Backup (Full) ähnelt.
        /// </summary>
        internal static string ManualBackupFull {
            get {
                return ResourceManager.GetString("ManualBackupFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual Backup (Selected Drivers) ähnelt.
        /// </summary>
        internal static string ManualBackupSelected {
            get {
                return ResourceManager.GetString("ManualBackupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize ähnelt.
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize to tray ähnelt.
        /// </summary>
        internal static string MinToTray {
            get {
                return ResourceManager.GetString("MinToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monday ähnelt.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More than ähnelt.
        /// </summary>
        internal static string MoreThan {
            get {
                return ResourceManager.GetString("MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Step ähnelt.
        /// </summary>
        internal static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N/A ähnelt.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Now scanning: ähnelt.
        /// </summary>
        internal static string NowScanning {
            get {
                return ResourceManager.GetString("NowScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OPTIONS ähnelt.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version 12.03 ähnelt.
        /// </summary>
        internal static string OSMigrationToolPopupBackupSubTitle {
            get {
                return ResourceManager.GetString("OSMigrationToolPopupBackupSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OS Migration Tool Backup Tool ähnelt.
        /// </summary>
        internal static string OSMigrationToolPopupBackupTitle {
            get {
                return ResourceManager.GetString("OSMigrationToolPopupBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version 12.03 ähnelt.
        /// </summary>
        internal static string OSMigrationToolPopupRestoreSubTitle {
            get {
                return ResourceManager.GetString("OSMigrationToolPopupRestoreSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OS Migration Tool Restore Tool ähnelt.
        /// </summary>
        internal static string OSMigrationToolPopupRestoreTitle {
            get {
                return ResourceManager.GetString("OSMigrationToolPopupRestoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OS Migration Tool ähnelt.
        /// </summary>
        internal static string OSMigrationToolPopupTitle {
            get {
                return ResourceManager.GetString("OSMigrationToolPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die outdated drivers found ähnelt.
        /// </summary>
        internal static string OutdatedDriversFound {
            get {
                return ResourceManager.GetString("OutdatedDriversFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outdated drivers updated! ähnelt.
        /// </summary>
        internal static string OutdatedDriversUpdated {
            get {
                return ResourceManager.GetString("OutdatedDriversUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Post this on: ähnelt.
        /// </summary>
        internal static string PostOn {
            get {
                return ResourceManager.GetString("PostOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preferences ähnelt.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage application settings ähnelt.
        /// </summary>
        internal static string PreferencesFooter {
            get {
                return ResourceManager.GetString("PreferencesFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can edit applications preferences and settings from this panel ähnelt.
        /// </summary>
        internal static string PreferencesFooterText {
            get {
                return ResourceManager.GetString("PreferencesFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reboot later ähnelt.
        /// </summary>
        internal static string RebootLater {
            get {
                return ResourceManager.GetString("RebootLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reboot now ähnelt.
        /// </summary>
        internal static string RebootNow {
            get {
                return ResourceManager.GetString("RebootNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reboot required ähnelt.
        /// </summary>
        internal static string RebootRequired {
            get {
                return ResourceManager.GetString("RebootRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove selected ähnelt.
        /// </summary>
        internal static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart your computer ähnelt.
        /// </summary>
        internal static string RestartYourComputer {
            get {
                return ResourceManager.GetString("RestartYourComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore drivers ähnelt.
        /// </summary>
        internal static string RestoreDrivers {
            get {
                return ResourceManager.GetString("RestoreDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore failed ähnelt.
        /// </summary>
        internal static string RestoreFailedCaption {
            get {
                return ResourceManager.GetString("RestoreFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfortunately the restore of the selected drivers failed. ähnelt.
        /// </summary>
        internal static string RestoreFailedText {
            get {
                return ResourceManager.GetString("RestoreFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore ähnelt.
        /// </summary>
        internal static string RestoreRadioBtnTitle {
            get {
                return ResourceManager.GetString("RestoreRadioBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore system drivers to one of the backups that you created earlier. ähnelt.
        /// </summary>
        internal static string RestoreText {
            get {
                return ResourceManager.GetString("RestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.freemium.com/fdu ähnelt.
        /// </summary>
        internal static string RootUrl {
            get {
                return ResourceManager.GetString("RootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore drivers ähnelt.
        /// </summary>
        internal static string RunOSMigrationRestoreTool {
            get {
                return ResourceManager.GetString("RunOSMigrationRestoreTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run OS Migration Tool ähnelt.
        /// </summary>
        internal static string RunOSMigrationTool {
            get {
                return ResourceManager.GetString("RunOSMigrationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saturday ähnelt.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save backups to this folder: ähnelt.
        /// </summary>
        internal static string SaveBackupsTo {
            get {
                return ResourceManager.GetString("SaveBackupsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save downloaded drivers to this folder: ähnelt.
        /// </summary>
        internal static string SaveDownloadedTo {
            get {
                return ResourceManager.GetString("SaveDownloadedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan: ähnelt.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan &amp; Update Drivers ähnelt.
        /// </summary>
        internal static string ScanAndUpdateDrivers {
            get {
                return ResourceManager.GetString("ScanAndUpdateDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan completed ähnelt.
        /// </summary>
        internal static string ScanCompleted {
            get {
                return ResourceManager.GetString("ScanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan Exclusions ähnelt.
        /// </summary>
        internal static string ScanExclusions {
            get {
                return ResourceManager.GetString("ScanExclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan your system regularly ähnelt.
        /// </summary>
        internal static string ScanFooter {
            get {
                return ResourceManager.GetString("ScanFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regular maintenance will help to improve system performance ähnelt.
        /// </summary>
        internal static string ScanFooterText {
            get {
                return ResourceManager.GetString("ScanFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan for Issues ähnelt.
        /// </summary>
        internal static string ScanForIssues {
            get {
                return ResourceManager.GetString("ScanForIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning device - ähnelt.
        /// </summary>
        internal static string ScanningDevice {
            get {
                return ResourceManager.GetString("ScanningDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SCAN PROGRESS ähnelt.
        /// </summary>
        internal static string ScanProgress {
            get {
                return ResourceManager.GetString("ScanProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Backup type ähnelt.
        /// </summary>
        internal static string SelectBackupType {
            get {
                return ResourceManager.GetString("SelectBackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please, select backup type to proceed. ähnelt.
        /// </summary>
        internal static string SelectBackupTypeText {
            get {
                return ResourceManager.GetString("SelectBackupTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select devices ähnelt.
        /// </summary>
        internal static string SelectDevices {
            get {
                return ResourceManager.GetString("SelectDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please, select devices you no longer wish to exclude from the scan. ähnelt.
        /// </summary>
        internal static string SelectDevicesToRemoveFromExclude {
            get {
                return ResourceManager.GetString("SelectDevicesToRemoveFromExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select drivers ähnelt.
        /// </summary>
        internal static string SelectDrivers {
            get {
                return ResourceManager.GetString("SelectDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT DRIVERS FOR BACKUP ähnelt.
        /// </summary>
        internal static string SelectDriversForBackup {
            get {
                return ResourceManager.GetString("SelectDriversForBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Why should I create Backups? ähnelt.
        /// </summary>
        internal static string SelectDriversForBackupFooter {
            get {
                return ResourceManager.GetString("SelectDriversForBackupFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove the exclusions you created in the Driver Scan ähnelt.
        /// </summary>
        internal static string SelectDriversForBackupFooterText {
            get {
                return ResourceManager.GetString("SelectDriversForBackupFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT DRIVERS FOR RESTORE ähnelt.
        /// </summary>
        internal static string SelectDriversForRestore {
            get {
                return ResourceManager.GetString("SelectDriversForRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select drivers for restore ähnelt.
        /// </summary>
        internal static string SelectDriversForRestoreCaption {
            get {
                return ResourceManager.GetString("SelectDriversForRestoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please, select at least one driver for restore. ähnelt.
        /// </summary>
        internal static string SelectDriversForRestoreText {
            get {
                return ResourceManager.GetString("SelectDriversForRestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please, select at least one driver to backup. ähnelt.
        /// </summary>
        internal static string SelectDriversToBackup {
            get {
                return ResourceManager.GetString("SelectDriversToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please, select at least one driver to update. ähnelt.
        /// </summary>
        internal static string SelectDriversToUpdate {
            get {
                return ResourceManager.GetString("SelectDriversToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select DriverData.zip ähnelt.
        /// </summary>
        internal static string SelectDriversZip {
            get {
                return ResourceManager.GetString("SelectDriversZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Select the folder for storing driver backups ähnelt.
        /// </summary>
        internal static string SelectFolderForBackups {
            get {
                return ResourceManager.GetString("SelectFolderForBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Select the folder for driver downloads ähnelt.
        /// </summary>
        internal static string SelectFolderForDownloads {
            get {
                return ResourceManager.GetString("SelectFolderForDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please, select DriverData.zip ähnelt.
        /// </summary>
        internal static string SelectMigrationDriversZip {
            get {
                return ResourceManager.GetString("SelectMigrationDriversZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: ähnelt.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sunday ähnelt.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thursday ähnelt.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time: ähnelt.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TIME &amp; DATE ähnelt.
        /// </summary>
        internal static string TimeAndDate {
            get {
                return ResourceManager.GetString("TimeAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die today ähnelt.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TotalSize ähnelt.
        /// </summary>
        internal static string TotalSize {
            get {
                return ResourceManager.GetString("TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tuesday ähnelt.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -50 ähnelt.
        /// </summary>
        internal static string TweetMargin {
            get {
                return ResourceManager.GetString("TweetMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tweet ähnelt.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.freemium.com/fsu/twitter ähnelt.
        /// </summary>
        internal static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driver update process completed for driver: ähnelt.
        /// </summary>
        internal static string UpdateCompleted {
            get {
                return ResourceManager.GetString("UpdateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driver update process failed for driver ähnelt.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting to update driver ähnelt.
        /// </summary>
        internal static string UpdateStart {
            get {
                return ResourceManager.GetString("UpdateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link cannot be opened automatically. Please open this Link in your favorite browser: ähnelt.
        /// </summary>
        internal static string UrlCannotBeOpenedMessage {
            get {
                return ResourceManager.GetString("UrlCannotBeOpenedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link cannot be opened automatically ähnelt.
        /// </summary>
        internal static string UrlCannotBeOpenedTitle {
            get {
                return ResourceManager.GetString("UrlCannotBeOpenedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VERSION ähnelt.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wednesday ähnelt.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Why should I create Backups? ähnelt.
        /// </summary>
        internal static string WhyCreateBackups {
            get {
                return ResourceManager.GetString("WhyCreateBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove the exclusions you created in the Driver Scan ähnelt.
        /// </summary>
        internal static string WhyCreateBackupsText {
            get {
                return ResourceManager.GetString("WhyCreateBackupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows startup behaviour: ähnelt.
        /// </summary>
        internal static string WindowsStartup {
            get {
                return ResourceManager.GetString("WindowsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freemium Driver Utilites Scan ähnelt.
        /// </summary>
        internal static string WindowsTaskRegistrationInfo {
            get {
                return ResourceManager.GetString("WindowsTaskRegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
